"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-28

Hand-written to match app/models.py exactly as of the Postgres migration
point -- NOT autogenerated (no live DB connection was available to
generate this against). Covers: users, rentals, verifications,
activations, deposit_intents, wallet_transactions (with the
rental_id/verification_id/activation_id/deposit_intent_id columns added
over the course of the Getatext -> TextVerified -> BloomSMS ->
TransactPay integrations).

Run this once against a FRESH Postgres database (no existing tables).
If you're migrating from the old SQLite dev setup, this is a fresh
start, not a data migration -- see the deployment notes for why that's
fine here (test data only).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

transaction_type_enum = sa.Enum(
    "deposit", "rental_charge", "rental_refund", "adjustment", name="transactiontype"
)
rental_status_enum = sa.Enum(
    "active", "completed", "cancelled", "failed", name="rentalstatus"
)
deposit_status_enum = sa.Enum("pending", "completed", "failed", name="depositstatus")


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("email", sa.String(), nullable=False, unique=True, index=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default=sa.false()),
        sa.Column("balance_cents", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )

    op.create_table(
        "rentals",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("getatext_id", sa.Integer(), nullable=True, index=True),
        sa.Column("service_api_name", sa.String(), nullable=False),
        sa.Column("service_display_name", sa.String(), nullable=True),
        sa.Column("number", sa.String(), nullable=True),
        sa.Column("cost_cents", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("charged_cents", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("status", rental_status_enum, nullable=False, server_default="active"),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("end_time", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )

    op.create_table(
        "verifications",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("textverified_id", sa.String(), nullable=True, index=True),
        sa.Column("service_api_name", sa.String(), nullable=False),
        sa.Column("service_display_name", sa.String(), nullable=True),
        sa.Column("number", sa.String(), nullable=True),
        sa.Column("cost_cents", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("charged_cents", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("status", rental_status_enum, nullable=False, server_default="active"),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )

    op.create_table(
        "activations",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("bloomsms_id", sa.String(), nullable=True, index=True),
        sa.Column("service_api_name", sa.String(), nullable=False),
        sa.Column("service_display_name", sa.String(), nullable=True),
        sa.Column("number", sa.String(), nullable=True),
        sa.Column("cost_cents", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("charged_cents", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("status", rental_status_enum, nullable=False, server_default="active"),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("end_time", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )

    op.create_table(
        "deposit_intents",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("reference", sa.String(), nullable=False, unique=True, index=True),
        sa.Column("amount_naira", sa.Float(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("fx_rate_used", sa.Float(), nullable=False),
        sa.Column("status", deposit_status_enum, nullable=False, server_default="pending"),
        sa.Column("transactpay_reference", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )

    op.create_table(
        "wallet_transactions",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("type", transaction_type_enum, nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("balance_after_cents", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("rental_id", sa.Integer(), sa.ForeignKey("rentals.id"), nullable=True),
        sa.Column("verification_id", sa.Integer(), sa.ForeignKey("verifications.id"), nullable=True),
        sa.Column("activation_id", sa.Integer(), sa.ForeignKey("activations.id"), nullable=True),
        sa.Column("deposit_intent_id", sa.Integer(), sa.ForeignKey("deposit_intents.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )


def downgrade() -> None:
    op.drop_table("wallet_transactions")
    op.drop_table("deposit_intents")
    op.drop_table("activations")
    op.drop_table("verifications")
    op.drop_table("rentals")
    op.drop_table("users")
    deposit_status_enum.drop(op.get_bind(), checkfirst=True)
    rental_status_enum.drop(op.get_bind(), checkfirst=True)
    transaction_type_enum.drop(op.get_bind(), checkfirst=True)
